


* CoSpaceRobot
Innovation, learning and competition. Introducing students to robotics.

** Requirements and Running

This project relies extensively on environment settings which **will not work with Apache/mod_wsgi setups**. It has been deployed successfully with both Gunicorn/Nginx and even uWSGI/Nginx.

*** Basics
The steps below will get you up and running with a local development environment. We assume you have the following installed:

- pip
- virtualenv
- PostgreSQL

You can change database to MySQL if you like, in the configure files.

First make sure to create and activate a virtualenv, then open a terminal at the project root and install the requirements for local development:

   #+BEGIN_SRC shell
    $ pip install -r requirements/local.txt
   #+END_SRC

Create a local PostgreSQL database::

   #+BEGIN_SRC shell
    $ createdb bolt
   #+END_SRC

Run ``migrate`` on your new database::

   #+BEGIN_SRC shell
    $ python manage.py migrate
   #+END_SRC

You can now run the ``runserver_plus`` command::

   #+BEGIN_SRC shell
    $ python manage.py runserver_plus
   #+END_SRC

Open up your browser to http://127.0.0.1:8000/ to see the site running locally.



*** OS Prerequisites
I'll come back and manage the doc later.
*** Development


** Contains
